version: '3'

services:

  db:
    image: mariadb
    restart: unless-stopped
    container_name: bairesdev-atcs-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atcs
      MYSQL_USER: atcs
      MYSQL_PASSWORD: atcs
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./db:/scripts
    working_dir: /scripts

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: unless-stopped
    container_name: bairesdev-atcs-api
    volumes:
      - ./docker/api/apache-site-atcs.conf:/etc/apache2/sites-available/atcs.conf
      - ./docker/api/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./api:/var/www/atcs-api
      - node-client-build:/var/www/atcs-client
    ports:
      - 8080:80
    depends_on:
      - db

  # client:
  #   build:
  #     context: .
  #     dockerfile: docker/client/Dockerfile
  #   container_name: bairesdev-atcs-client
  #   volumes:
      # - node-client-build:/app/build

volumes:
  mariadb-data:
  node-client-build:

networks:
  default:
    name: bairesdev-atcs
