version: '3'

services:

  db:
    image: mariadb
    restart: unless-stopped
    container_name: bairesdev-atcs-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atcs
      MYSQL_USER: atcs
      MYSQL_PASSWORD: atcs
    volumes:
      - mariadb-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    container_name: bairesdev-atcs-phalcon
    volumes:
      - ./docker/apache-site-atcs.conf:/etc/apache2/sites-available/atcs.conf
      - ./docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./api:/var/www/atcs/api
      - ./client/build:/var/www/atcs/client
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  mariadb-data:

networks:
  default:
    name: bairesdev-atcs
